### ISSUE TITLE
[BUG] Remove warnings

### ISSUE THREAD

**Issue by lorenzo-rovigatti** [demonico85/cleaving#2]
The code issues quite a few warnings related to the return values of `fscanf` and `fread`. We should try to get rid of those so that we don't clutter the output. I think one way of doing it is to use LAMMPS' `utils::sfread` function.

**Comment by demonico85** [comment]
Updated all the fread with LAMMPS utils `utils::sfread`. The code does not issue any more warnings upon compilation
